name: Testing API
on: [push, pull_request]
jobs: 
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Creating and activating virtualenv
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Install dependencies 
        run: |
          pip install dvc[gdrive]
          pip install -r requirements_test.txt
      - name: Test API
        run: |
          export GDRIVE_CREDENTIALS_DATA=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
          pytest test.py 
